### ISSUE TITLE
Errors when joining on multiple required (list) key columns

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe-postgres-fdw#27] opened 2021-03-11 16:24 UTC
Only seems to occur when joining to table that has multiple `keyColumns` defined for `List` - I think `aws_iam_policy_simulator` may be the only such table currently:

```sql
select
    u.name as username,
    s.decision,
    jsonb_pretty(s.matched_statements)
from
    aws_iam_user as u,
    aws_iam_policy_simulator as s
where
    s.action = 's3:DeleteBucket'
    and s.resource_arn = '*';

Error: 'List' call requires an '=' qual for all columns: principal_arn,action,resource_arn
```

**Comment by kaidaguerre** [comment] 2021-03-11 17:17
This was caused by duplicate quals being passed to the plugin. Fixed by https://github.com/turbot/steampipe-postgres-fdw/commit/1d90a2d4f91a65369282080ee3b80c83eb94b435

**Closed** 2021-06-10 11:41 UTC
Labels: bug, quals
